// Copyright (c) Microsoft Corporation. All rights reserved. Licensed under the MIT license.
// See LICENSE in the project root for license information.

import * as path from 'path';
import { FileSystem, Terminal } from '@rushstack/node-core-library';

import { IHeftPlugin } from '../../pluginFramework/IHeftPlugin';
import { HeftSession } from '../../pluginFramework/HeftSession';
import { HeftConfiguration } from '../../configuration/HeftConfiguration';
import { ApiExtractorRunner } from './ApiExtractorRunner';
import { IBuildStageContext, IBundleSubstage } from '../../stages/BuildStage';
import { HeftConfigFiles } from '../../utilities/HeftConfigFiles';

const PLUGIN_NAME: string = 'ApiExtractorPlugin';
const CONFIG_FILE_LOCATION: string = './config/api-extractor.json';

export interface IApiExtractorPluginConfiguration {
  /**
   * If set to true, use the project's TypeScript compiler version for API Extractor's
   * analysis. API Extractor's included TypeScript compiler can generally correctly
   * analyze typings generated by older compilers, and referencing the project's compiler
   * can cause issues. If issues are encountered with API Extractor's included compiler,
   * set this option to true.
   *
   * This corresponds to API Extractor's `--typescript-compiler-folder` CLI option and
   * `IExtractorInvokeOptions.typescriptCompilerFolder` API option. This option defaults to false.
   */
  useProjectTypescriptVersion?: boolean;
}

interface IRunApiExtractorOptions {
  heftConfiguration: HeftConfiguration;
  buildFolder: string;
  debugMode: boolean;
  watchMode: boolean;
  production: boolean;
}

export class ApiExtractorPlugin implements IHeftPlugin {
  public readonly pluginName: string = PLUGIN_NAME;

  public apply(heftSession: HeftSession, heftConfiguration: HeftConfiguration): void {
    const { buildFolder } = heftConfiguration;
    if (FileSystem.exists(path.join(buildFolder, CONFIG_FILE_LOCATION))) {
      heftSession.hooks.build.tap(PLUGIN_NAME, (build: IBuildStageContext) => {
        build.hooks.bundle.tap(PLUGIN_NAME, (bundle: IBundleSubstage) => {
          bundle.hooks.run.tapPromise(PLUGIN_NAME, async () => {
            await this._runApiExtractorAsync(heftSession, {
              heftConfiguration,
              buildFolder,
              debugMode: heftSession.debugMode,
              watchMode: build.properties.watchMode,
              production: build.properties.production
            });
          });
        });
      });
    }
  }

  private async _runApiExtractorAsync(
    heftSession: HeftSession,
    options: IRunApiExtractorOptions
  ): Promise<void> {
    const { heftConfiguration, buildFolder, debugMode, watchMode, production } = options;

    let apiExtractorTaskConfiguration: IApiExtractorPluginConfiguration | undefined;
    try {
      apiExtractorTaskConfiguration = await HeftConfigFiles.apiExtractorTaskConfigurationLoader.loadConfigurationFileAsync(
        path.resolve(heftConfiguration.buildFolder, '.heft', 'api-extractor-task.json')
      );
    } catch (e) {
      if (!FileSystem.isNotExistError(e)) {
        throw e;
      }
    }

    const terminal: Terminal = ApiExtractorRunner.getTerminal(heftConfiguration.terminalProvider);

    if (watchMode) {
      terminal.writeWarningLine("API Extractor isn't currently supported in --watch mode.");
      return;
    }

    if (!heftConfiguration.compilerPackage) {
      throw new Error('Unable to resolve a compiler package for tsconfig.json');
    }

    if (!heftConfiguration.compilerPackage.apiExtractorPackagePath) {
      throw new Error('Unable to resolve the "@microsoft/api-extractor" package for this project');
    }

    const apiExtractorRunner: ApiExtractorRunner = new ApiExtractorRunner(
      heftConfiguration.terminalProvider,
      {
        configFileLocation: CONFIG_FILE_LOCATION,
        apiExtractorPackagePath: heftConfiguration.compilerPackage.apiExtractorPackagePath,
        typescriptPackagePath: apiExtractorTaskConfiguration?.useProjectTypescriptVersion
          ? heftConfiguration.compilerPackage.typeScriptPackagePath
          : undefined,
        buildFolder: buildFolder,
        production: production
      },
      heftSession
    );
    if (debugMode) {
      await apiExtractorRunner.invokeAsync();
    } else {
      await apiExtractorRunner.invokeAsSubprocessAsync();
    }
  }
}
