#!/bin/sh
# This script follows the same pattern as an NPM binary wrapper for non-Windows

echo "Executing npm-binary-wrapper with args:"
echo "$@"

basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

node  "$basedir/javascript-file.js" "$@"
ret=$?

exit $ret
