version: 2

# Group settings to apply to all groups by default, optionally being overridden later
group_defaults:
  approve_by_comment:
    enabled: true
    approve_regex: '^(Approved|:shipit:)'
    reject_regex: '^(Rejected)'

groups:
  pullapprove-admins:
    conditions:
      files:
        - ".pullapprove.yml"
        - ".travis.yml"
    required: 1
    users:
      - iclanton
      - nickpape-msft
      - pgonzal
      - patmill
      - aditima

  api-approvers:
    conditions:
      files:
        - "common/reviews/*"
    required: 1
    users:
      - iclanton
      - nickpape-msft
      - pgonzal
      - mpasarin
      - aditima

  general-approvers:
    conditions:
      files:
        - "apps/*"
        - "build-tests/*"
        - "core-build/*"
        - "libraries/*"
        - "webpack/*"
        - "rush.json"
        - ".gitattributes"
        - ".gitignore"
        - "README.md"
    required: 1
    users:
      - iclanton
      - nickpape-msft
      - pgonzal
      - aditima

  load-themed-styles-approvers:
    conditions:
      files:
        - "libraries/load-themed-styles/*"
    required: 1
    users:
      - iclanton
      - nickpape-msft
      - pgonzal
      - dzearing
      - aditima
