#!/bin/sh
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.

node common/scripts/install-run-rush.js prettier --staged $* || exit $?
