// Copyright (c) Microsoft Corporation. All rights reserved. Licensed under the MIT license.
// See LICENSE in the project root for license information.

import * as fs from 'node:fs';
import * as path from 'node:path';

/**
 * This module evaluates a small subset of glob patterns without loading fast-glob (which costs ~70 modules
 * at startup). It is used for the patterns that Heft generates most commonly (clean operations, file
 * extension selections, etc.) and produces exactly the entries that fast-glob would produce when called by
 * `getFileSelectionSpecifierPathsAsync()` with `{ dot: true, absolute: true, objectMode: true }` and no custom
 * file system adapter or ignore patterns.
 *
 * Whenever a pattern, a file system entry, or an error falls outside of what is modeled here (for example
 * symbolic links, unusual characters, or any error other than a missing path), `undefined` is returned and the
 * caller falls back to fast-glob, which then produces its usual results or errors. Since evaluating globs has no
 * side effects, falling back after a partial evaluation is safe.
 */

type ISimplePattern =
  // A pattern without glob syntax, e.g. "lib" or "temp/build". fast-glob stats these directly.
  | { kind: 'literal'; relativePath: string }
  // "**/*" (recursive) or "*" (top level only)
  | { kind: 'any'; recursive: boolean }
  // "**/*<suffix>", e.g. "**/*.json": matches entries at any depth whose name ends with the suffix
  | { kind: 'suffix'; suffix: string }
  // "<prefix>*", e.g. "build.*": matches top-level entries whose name starts with the prefix
  | { kind: 'prefix'; prefix: string };

// A literal path segment that fast-glob treats as static and matches verbatim.
const LITERAL_SEGMENT_REGEXP: RegExp = /^[A-Za-z0-9_.-]+$/;
const DOTS_ONLY_REGEXP: RegExp = /^\.+$/;
// A file extension (without the leading dot) that has no special meaning in globs or brace expansions.
const EXTENSION_REGEXP: RegExp = /^[A-Za-z0-9_-]+(?:\.[A-Za-z0-9_-]+)*$/;
const RECURSIVE_EXTENSION_PATTERN_REGEXP: RegExp = /^\*\*\/\*\.([^/{}]+)$/;
const RECURSIVE_EXTENSION_LIST_PATTERN_REGEXP: RegExp = /^\*\*\/\*\.\{([^/{}]+)\}$/;
const PREFIX_PATTERN_REGEXP: RegExp = /^([A-Za-z0-9_-]+(?:\.[A-Za-z0-9_-]+)*\.)\*$/;
// Entry names that fast-glob may treat differently: line terminators are not matched by "." in the regular
// expressions generated by micromatch, and backslashes are rewritten by fast-glob's path normalization.
const UNSUPPORTED_NAME_CHARACTERS_REGEXP: RegExp = /[\\\n\r\u2028\u2029]/;

function parsePattern(pattern: unknown): ISimplePattern[] | undefined {
  if (typeof pattern !== 'string') {
    return undefined;
  }

  if (pattern === '**/*') {
    return [{ kind: 'any', recursive: true }];
  }

  if (pattern === '*') {
    return [{ kind: 'any', recursive: false }];
  }

  let match: RegExpExecArray | null = RECURSIVE_EXTENSION_PATTERN_REGEXP.exec(pattern);
  if (match) {
    const extension: string = match[1];
    return EXTENSION_REGEXP.test(extension) ? [{ kind: 'suffix', suffix: `.${extension}` }] : undefined;
  }

  match = RECURSIVE_EXTENSION_LIST_PATTERN_REGEXP.exec(pattern);
  if (match) {
    // fast-glob expands braces into one pattern per alternative
    const extensions: string[] = match[1].split(',');
    if (extensions.length < 2 || !extensions.every((extension) => EXTENSION_REGEXP.test(extension))) {
      return undefined;
    }
    return extensions.map((extension) => ({ kind: 'suffix', suffix: `.${extension}` }));
  }

  match = PREFIX_PATTERN_REGEXP.exec(pattern);
  if (match) {
    return [{ kind: 'prefix', prefix: match[1] }];
  }

  const segments: string[] = pattern.split('/');
  for (const segment of segments) {
    if (!LITERAL_SEGMENT_REGEXP.test(segment) || DOTS_ONLY_REGEXP.test(segment)) {
      return undefined;
    }
  }

  return [{ kind: 'literal', relativePath: pattern }];
}

/**
 * Same shape as the objects that fast-glob creates for entries that it obtains via `fs.lstat()`.
 */
class DirentFromStats {
  public readonly name: string;
  public readonly isBlockDevice: () => boolean;
  public readonly isCharacterDevice: () => boolean;
  public readonly isDirectory: () => boolean;
  public readonly isFIFO: () => boolean;
  public readonly isFile: () => boolean;
  public readonly isSocket: () => boolean;
  public readonly isSymbolicLink: () => boolean;

  public constructor(name: string, stats: fs.Stats) {
    this.name = name;
    this.isBlockDevice = stats.isBlockDevice.bind(stats);
    this.isCharacterDevice = stats.isCharacterDevice.bind(stats);
    this.isDirectory = stats.isDirectory.bind(stats);
    this.isFIFO = stats.isFIFO.bind(stats);
    this.isFile = stats.isFile.bind(stats);
    this.isSocket = stats.isSocket.bind(stats);
    this.isSymbolicLink = stats.isSymbolicLink.bind(stats);
  }
}

function isNotExistError(error: NodeJS.ErrnoException): boolean {
  return error.code === 'ENOENT';
}

function lstatAsync(filePath: string): Promise<fs.Stats | undefined | false> {
  return new Promise((resolve) => {
    fs.lstat(filePath, (error: NodeJS.ErrnoException | null, stats: fs.Stats) => {
      if (error) {
        // A missing path produces no entry; any other error is left to fast-glob.
        resolve(isNotExistError(error) ? undefined : false);
      } else {
        resolve(stats);
      }
    });
  });
}

function readFolderAsync(folderPath: string): Promise<fs.Dirent[] | undefined | false> {
  return new Promise((resolve) => {
    fs.readdir(folderPath, { withFileTypes: true }, (error: NodeJS.ErrnoException | null, dirents) => {
      if (error) {
        resolve(isNotExistError(error) ? undefined : false);
      } else {
        resolve(dirents);
      }
    });
  });
}

// Same as the path joining performed by fast-glob's directory walker, which always uses '/'.
function joinPathSegments(a: string, b: string): string {
  if (a === '') {
    return b;
  }
  return a.endsWith('/') ? a + b : `${a}/${b}`;
}

// Same as the absolute path transformation performed by fast-glob.
function toAbsolutePath(cwd: string, relativePath: string): string {
  return path.resolve(cwd, relativePath).replace(/\\/g, '/');
}

interface IFolderToRead {
  folderPath: string;
  relativeFolderPath: string;
}

/**
 * Returns the same entries that fast-glob would return (in objectMode, with `dot: true` and `absolute: true`)
 * for the specified patterns, or `undefined` if the patterns or the file system contents are not supported.
 */
export async function trySimpleGlobAsync(
  patterns: unknown,
  cwd: unknown,
  onlyFiles: boolean
): Promise<Map<string, fs.Dirent> | undefined> {
  if (!Array.isArray(patterns) || patterns.length === 0 || typeof cwd !== 'string' || cwd === '') {
    return undefined;
  }

  const literalPaths: string[] = [];
  let matchAnyRecursive: boolean = false;
  let matchAnyTopLevel: boolean = false;
  const suffixes: string[] = [];
  const prefixes: string[] = [];
  for (const pattern of patterns) {
    const simplePatterns: ISimplePattern[] | undefined = parsePattern(pattern);
    if (!simplePatterns) {
      return undefined;
    }

    for (const simplePattern of simplePatterns) {
      switch (simplePattern.kind) {
        case 'literal':
          literalPaths.push(simplePattern.relativePath);
          break;
        case 'any':
          if (simplePattern.recursive) {
            matchAnyRecursive = true;
          } else {
            matchAnyTopLevel = true;
          }
          break;
        case 'suffix':
          suffixes.push(simplePattern.suffix);
          break;
        case 'prefix':
          prefixes.push(simplePattern.prefix);
          break;
      }
    }
  }

  const isRecursive: boolean = matchAnyRecursive || suffixes.length > 0;
  const hasDynamicPatterns: boolean = isRecursive || matchAnyTopLevel || prefixes.length > 0;

  // Relative path -> entry. fast-glob de-duplicates entries by their relative path.
  const entriesByRelativePath: Map<string, fs.Dirent> = new Map();

  const literalStats: (fs.Stats | undefined | false)[] = await Promise.all(
    literalPaths.map((literalPath: string) => lstatAsync(path.resolve(cwd, literalPath)))
  );
  for (let i: number = 0; i < literalPaths.length; i++) {
    const stats: fs.Stats | undefined | false = literalStats[i];
    if (stats === false || (stats && stats.isSymbolicLink())) {
      return undefined;
    }
    if (stats && (!onlyFiles || stats.isFile())) {
      const literalPath: string = literalPaths[i];
      if (!entriesByRelativePath.has(literalPath)) {
        entriesByRelativePath.set(
          literalPath,
          new DirentFromStats(literalPath, stats) as unknown as fs.Dirent
        );
      }
    }
  }

  if (hasDynamicPatterns) {
    let foldersToRead: IFolderToRead[] = [{ folderPath: path.resolve(cwd), relativeFolderPath: '' }];
    let isTopLevel: boolean = true;
    while (foldersToRead.length > 0) {
      const folderContents: (fs.Dirent[] | undefined | false)[] = await Promise.all(
        foldersToRead.map(({ folderPath }) => readFolderAsync(folderPath))
      );

      const nextFoldersToRead: IFolderToRead[] = [];
      for (let i: number = 0; i < foldersToRead.length; i++) {
        const dirents: fs.Dirent[] | undefined | false = folderContents[i];
        if (dirents === false) {
          return undefined;
        }
        if (dirents === undefined) {
          if (isTopLevel) {
            // fast-glob ignores a missing root folder
            continue;
          }
          // A folder was removed while it was being read
          return undefined;
        }

        const { folderPath, relativeFolderPath } = foldersToRead[i];
        for (const dirent of dirents) {
          const { name } = dirent;
          if (dirent.isSymbolicLink() || UNSUPPORTED_NAME_CHARACTERS_REGEXP.test(name)) {
            return undefined;
          }

          const relativePath: string = joinPathSegments(relativeFolderPath, name);
          const isMatch: boolean =
            matchAnyRecursive ||
            (isTopLevel && matchAnyTopLevel) ||
            suffixes.some((suffix: string) => name.endsWith(suffix)) ||
            (isTopLevel && prefixes.some((prefix: string) => name.startsWith(prefix)));
          if (isMatch && (!onlyFiles || dirent.isFile()) && !entriesByRelativePath.has(relativePath)) {
            entriesByRelativePath.set(relativePath, dirent);
          }

          if (isRecursive && dirent.isDirectory()) {
            nextFoldersToRead.push({
              folderPath: joinPathSegments(folderPath, name),
              relativeFolderPath: relativePath
            });
          }
        }
      }

      foldersToRead = nextFoldersToRead;
      isTopLevel = false;
    }
  }

  const results: Map<string, fs.Dirent> = new Map();
  for (const [relativePath, dirent] of entriesByRelativePath) {
    results.set(toAbsolutePath(cwd, relativePath), dirent);
  }
  return results;
}
