// Copyright (c) Microsoft Corporation. All rights reserved. Licensed under the MIT license.
// See LICENSE in the project root for license information.

import * as path from 'node:path';

import type { IRunScriptOptions } from '@rushstack/heft';
import { Async, FileSystem, type FolderItem, Import, JsonFile, Path } from '@rushstack/node-core-library';

interface IGenerateJsStubsOptions {
  parentSourcePath: string;
  parentTargetPath: string;
  parentSrcImportPathWithSlash: string;
  libShimIndexPath: string;
}

interface IJsStubTask {
  jsSourcePath: string;
  targetPath: string;
  srcImportPath: string;
  shimPathLiteral: string;
}

/**
 * Walks rush-lib/lib-commonjs to collect JS stub tasks. These stubs redirect
 * require() calls through the rush-sdk shim so that the actual rush-lib module
 * is loaded at runtime.
 */
async function* collectJsStubTasksAsync(options: IGenerateJsStubsOptions): AsyncGenerator<IJsStubTask> {
  const { parentSourcePath, parentTargetPath, parentSrcImportPathWithSlash, libShimIndexPath } = options;
  const folderItems: FolderItem[] = await FileSystem.readFolderItemsAsync(parentSourcePath);

  for (const folderItem of folderItems) {
    const itemName: string = folderItem.name;
    const sourcePath: string = `${parentSourcePath}/${itemName}`;
    const targetPath: string = `${parentTargetPath}/${itemName}`;

    if (folderItem.isDirectory()) {
      // Ensure destination folder exists
      await FileSystem.ensureFolderAsync(targetPath);
      // Recursively yield tasks from subdirectory
      yield* collectJsStubTasksAsync({
        parentSourcePath: sourcePath,
        parentTargetPath: targetPath,
        parentSrcImportPathWithSlash: parentSrcImportPathWithSlash + itemName + '/',
        libShimIndexPath
      });
    } else if (folderItem.name.endsWith('.js')) {
      const srcImportPath: string = parentSrcImportPathWithSlash + path.parse(folderItem.name).name;
      const shimPath: string = path.relative(parentTargetPath, libShimIndexPath);
      const shimPathLiteral: string = JSON.stringify(Path.convertToSlashes(shimPath));

      yield {
        jsSourcePath: sourcePath,
        targetPath,
        srcImportPath,
        shimPathLiteral
      };
    }
  }
}

async function processJsStubTaskAsync(task: IJsStubTask): Promise<void> {
  const { jsSourcePath, targetPath, srcImportPath, shimPathLiteral } = task;
  const srcImportPathLiteral: string = JSON.stringify(srcImportPath);

  let namedExportsAssignment: string = '';
  try {
    // Read the sidecar .exports.json file generated by DeepImportsPlugin to get module exports
    const exportsJsonPath: string = jsSourcePath.slice(0, -'.js'.length) + '.exports.json';
    const { moduleExports }: { moduleExports: string[] } = await JsonFile.loadAsync(exportsJsonPath);
    if (moduleExports.length > 0) {
      // Assign named exports after module.exports to ensure they're properly exposed for ESM imports
      namedExportsAssignment =
        '\n' + moduleExports.map((exportName) => `exports.${exportName} = _m.${exportName};`).join('\n');
    }
  } catch (e) {
    if (!FileSystem.isNotExistError(e)) {
      throw e;
    }
  }

  await FileSystem.writeFileAsync(
    targetPath,
    // Example:
    // ```
    // const _m = require("../../../lib-shim/index")._rushSdk_loadInternalModule("logic/policy/GitEmailPolicy");
    // module.exports = _m;
    // exports.GitEmailPolicy = _m.GitEmailPolicy;
    // ```
    `const _m = require(${shimPathLiteral})._rushSdk_loadInternalModule(${srcImportPathLiteral});\nmodule.exports = _m;${namedExportsAssignment}\n`
  );
}

// Entry point invoked by "runScript" action from config/heft.json
export async function runAsync(options: IRunScriptOptions): Promise<void> {
  const {
    heftConfiguration: { buildFolderPath },
    heftTaskSession: {
      logger: { terminal }
    }
  } = options;

  const rushLibFolder: string = Import.resolvePackage({
    baseFolderPath: __dirname,
    packageName: '@microsoft/rush-lib',
    useNodeJSResolver: true
  });

  const cjsStubsTargetPath: string = `${buildFolderPath}/lib-commonjs`;
  terminal.writeLine(`generate-stubs: Generating stub files under ${cjsStubsTargetPath}`);

  // Ensure the target folder exists
  await FileSystem.ensureFolderAsync(cjsStubsTargetPath);

  // Generate JS stubs from rush-lib/lib-commonjs (these redirect require() through the shim)
  // Note: .d.ts files are copied separately by the copy-rush-lib-types heft task from rush-lib/lib-dts
  const jsTasks: AsyncGenerator<IJsStubTask> = collectJsStubTasksAsync({
    parentSourcePath: `${rushLibFolder}/lib-commonjs`,
    parentTargetPath: cjsStubsTargetPath,
    parentSrcImportPathWithSlash: '',
    libShimIndexPath: `${buildFolderPath}/lib-shim/index.js`
  });
  await Async.forEachAsync(jsTasks, processJsStubTaskAsync, { concurrency: 50 });

  terminal.writeLine('generate-stubs: Completed successfully.');
}
