// Copyright (c) Microsoft Corporation. All rights reserved. Licensed under the MIT license.
// See LICENSE in the project root for license information.

import * as path from 'node:path';

import type { IRunScriptOptions } from '@rushstack/heft';
import { Async, FileSystem, type FolderItem, Import, JsonFile, Path } from '@rushstack/node-core-library';

interface IGenerateOptions {
  parentSourcePath: string;
  parentTargetPath: string;
  parentSrcImportPathWithSlash: string;
  libShimIndexPath: string;
}

interface IFileTask {
  type: 'dts' | 'js';
  sourcePath: string;
  targetPath: string;
  srcImportPath?: string;
  shimPathLiteral?: string;
}

async function* collectFileTasksAsync(options: IGenerateOptions): AsyncGenerator<IFileTask> {
  const { parentSourcePath, parentTargetPath, parentSrcImportPathWithSlash, libShimIndexPath } = options;
  const folderItems: FolderItem[] = await FileSystem.readFolderItemsAsync(options.parentSourcePath);

  for (const folderItem of folderItems) {
    const itemName: string = folderItem.name;
    const sourcePath: string = `${parentSourcePath}/${itemName}`;
    const targetPath: string = `${parentTargetPath}/${itemName}`;

    if (folderItem.isDirectory()) {
      // Ensure destination folder exists
      await FileSystem.ensureFolderAsync(targetPath);
      // Recursively yield tasks from subdirectory
      yield* collectFileTasksAsync({
        parentSourcePath: sourcePath,
        parentTargetPath: targetPath,
        parentSrcImportPathWithSlash: parentSrcImportPathWithSlash + itemName + '/',
        libShimIndexPath
      });
    } else if (folderItem.name.endsWith('.d.ts')) {
      yield {
        type: 'dts',
        sourcePath,
        targetPath
      };
    } else if (folderItem.name.endsWith('.js')) {
      const srcImportPath: string = parentSrcImportPathWithSlash + path.parse(folderItem.name).name;
      const shimPath: string = path.relative(parentTargetPath, libShimIndexPath);
      const shimPathLiteral: string = JSON.stringify(Path.convertToSlashes(shimPath));

      yield {
        type: 'js',
        sourcePath,
        targetPath,
        srcImportPath,
        shimPathLiteral
      };
    }
  }
}

async function processFileTaskAsync(task: IFileTask): Promise<void> {
  const { type, sourcePath, targetPath, srcImportPath, shimPathLiteral } = task;
  if (type === 'dts') {
    await FileSystem.copyFileAsync({
      sourcePath,
      destinationPath: targetPath
    });
  } else {
    const srcImportPathLiteral: string = JSON.stringify(srcImportPath);

    let namedExportsAssignment: string = '';
    try {
      // Read the sidecar .exports.json file generated by DeepImportsPlugin to get module exports
      const exportsJsonPath: string = sourcePath.slice(0, -'.js'.length) + '.exports.json';
      const { moduleExports }: { moduleExports: string[] } = await JsonFile.loadAsync(exportsJsonPath);
      if (moduleExports.length > 0) {
        // Assign named exports after module.exports to ensure they're properly exposed for ESM imports
        namedExportsAssignment =
          '\n' + moduleExports.map((exportName) => `exports.${exportName} = _m.${exportName};`).join('\n');
      }
    } catch (e) {
      if (!FileSystem.isNotExistError(e)) {
        throw e;
      }
    }

    await FileSystem.writeFileAsync(
      targetPath,
      // Example:
      // ```
      // const _m = require("../../../lib-shim/index")._rushSdk_loadInternalModule("logic/policy/GitEmailPolicy");
      // module.exports = _m;
      // exports.GitEmailPolicy = _m.GitEmailPolicy;
      // ```
      `const _m = require(${shimPathLiteral})._rushSdk_loadInternalModule(${srcImportPathLiteral});\nmodule.exports = _m;${namedExportsAssignment}\n`
    );
  }
}

// Entry point invoked by "runScript" action from config/heft.json
export async function runAsync(options: IRunScriptOptions): Promise<void> {
  const {
    heftConfiguration: { buildFolderPath },
    heftTaskSession: {
      logger: { terminal }
    }
  } = options;

  const rushLibFolder: string = Import.resolvePackage({
    baseFolderPath: __dirname,
    packageName: '@microsoft/rush-lib',
    useNodeJSResolver: true
  });

  const stubsTargetPath: string = `${buildFolderPath}/lib`;
  terminal.writeLine('generate-stubs: Generating stub files under: ' + stubsTargetPath);

  // Ensure the target folder exists
  await FileSystem.ensureFolderAsync(stubsTargetPath);

  // Collect and process file tasks in parallel with controlled concurrency
  const tasks: AsyncGenerator<IFileTask> = collectFileTasksAsync({
    parentSourcePath: `${rushLibFolder}/lib`,
    parentTargetPath: stubsTargetPath,
    parentSrcImportPathWithSlash: '',
    libShimIndexPath: `${buildFolderPath}/lib-shim/index.js`
  });
  await Async.forEachAsync(tasks, processFileTaskAsync, { concurrency: 50 });

  terminal.writeLine('generate-stubs: Completed successfully.');
}
