// Copyright (c) Microsoft Corporation. All rights reserved. Licensed under the MIT license.
// See LICENSE in the project root for license information.

import * as path from 'node:path';

import type {
  CommandLineFlagParameter,
  CommandLineStringParameter,
  CommandLineChoiceParameter
} from '@rushstack/ts-command-line';
import { FileSystem } from '@rushstack/node-core-library';
import { RigConfig } from '@rushstack/rig-package';
import { Colorize, ConsoleTerminalProvider, Terminal } from '@rushstack/terminal';

import { type IChangeInfo, ChangeType } from '../../api/ChangeManagement';
import { type IPublishJson, PUBLISH_CONFIGURATION_FILE } from '../../api/PublishConfiguration';
import type { RushConfigurationProject } from '../../api/RushConfigurationProject';
import type { RushCommandLineParser } from '../RushCommandLineParser';
import { PublishUtilities } from '../../logic/PublishUtilities';
import { ChangelogGenerator } from '../../logic/ChangelogGenerator';
import { PrereleaseToken } from '../../logic/PrereleaseToken';
import { ChangeManager } from '../../logic/ChangeManager';
import { BaseRushAction } from './BaseRushAction';
import { PublishGit } from '../../logic/PublishGit';
import * as PolicyValidator from '../../logic/policy/PolicyValidator';
import type { IPublishProvider } from '../../pluginFramework/IPublishProvider';
import { Logger } from '../../pluginFramework/logging/Logger';
import type { VersionPolicy } from '../../api/VersionPolicy';
import { DEFAULT_PACKAGE_UPDATE_MESSAGE } from './VersionAction';
import { Utilities } from '../../utilities/Utilities';
import { Git } from '../../logic/Git';
import { RushConstants } from '../../logic/RushConstants';

export class PublishAction extends BaseRushAction {
  private readonly _addCommitDetails: CommandLineFlagParameter;
  private readonly _apply: CommandLineFlagParameter;
  private readonly _includeAll: CommandLineFlagParameter;
  private readonly _npmAuthToken: CommandLineStringParameter;
  private readonly _npmTag: CommandLineStringParameter;
  private readonly _npmAccessLevel: CommandLineChoiceParameter;
  private readonly _publish: CommandLineFlagParameter;
  private readonly _regenerateChangelogs: CommandLineFlagParameter;
  private readonly _registryUrl: CommandLineStringParameter;
  private readonly _targetBranch: CommandLineStringParameter;
  private readonly _prereleaseName: CommandLineStringParameter;
  private readonly _partialPrerelease: CommandLineFlagParameter;
  private readonly _suffix: CommandLineStringParameter;
  private readonly _force: CommandLineFlagParameter;
  private readonly _versionPolicy: CommandLineStringParameter;
  private readonly _applyGitTagsOnPack: CommandLineFlagParameter;
  private readonly _commitId: CommandLineStringParameter;
  private readonly _releaseFolder: CommandLineStringParameter;
  private readonly _pack: CommandLineFlagParameter;
  private readonly _ignoreGitHooksParameter: CommandLineFlagParameter;

  private _prereleaseToken!: PrereleaseToken;
  private _hotfixTagOverride!: string;
  private _targetNpmrcPublishFolder!: string;
  private readonly _publishConfigCache: Map<string, IPublishJson | undefined> = new Map();
  private readonly _providerCache: Map<string, IPublishProvider> = new Map();

  public constructor(parser: RushCommandLineParser) {
    super({
      actionName: 'publish',
      summary: 'Reads and processes package publishing change requests generated by "rush change".',
      documentation:
        'Reads and processes package publishing change requests generated by "rush change". This will perform a ' +
        'read-only operation by default, printing operations executed to the console. To commit ' +
        'changes and publish packages, you must use the --commit flag and/or the --publish flag.',
      parser
    });

    this._apply = this.defineFlagParameter({
      parameterLongName: '--apply',
      parameterShortName: '-a',
      description: 'If this flag is specified, the change requests will be applied to package.json files.'
    });
    this._targetBranch = this.defineStringParameter({
      parameterLongName: '--target-branch',
      parameterShortName: '-b',
      argumentName: 'BRANCH',
      description:
        'If this flag is specified, applied changes and deleted change requests will be ' +
        'committed and merged into the target branch.'
    });
    this._publish = this.defineFlagParameter({
      parameterLongName: '--publish',
      parameterShortName: '-p',
      description: 'If this flag is specified, applied changes will be published to the NPM registry.'
    });
    this._addCommitDetails = this.defineFlagParameter({
      parameterLongName: '--add-commit-details',
      parameterShortName: undefined,
      description: 'Adds commit author and hash to the changelog.json files for each change.'
    });
    this._regenerateChangelogs = this.defineFlagParameter({
      parameterLongName: '--regenerate-changelogs',
      parameterShortName: undefined,
      description: 'Regenerates all changelog files based on the current JSON content.'
    });

    // NPM registry related parameters
    this._registryUrl = this.defineStringParameter({
      parameterLongName: '--registry',
      parameterShortName: '-r',
      argumentName: 'REGISTRY',
      description:
        `Publishes to a specified NPM registry. If this is specified, it will prevent the current commit will not be ` +
        'tagged.'
    });
    this._npmAuthToken = this.defineStringParameter({
      parameterLongName: '--npm-auth-token',
      parameterShortName: '-n',
      argumentName: 'TOKEN',
      description:
        '(DEPRECATED) Specifies the authentication token to use during publishing. This parameter is deprecated' +
        ' because command line parameters may be readable by unrelated processes on a lab machine. Instead, a' +
        ' safer practice is to pass the token via an environment variable and reference it from your ' +
        ' common/config/rush/.npmrc-publish file.'
    });
    this._npmTag = this.defineStringParameter({
      parameterLongName: '--tag',
      parameterShortName: '-t',
      argumentName: 'TAG',
      description:
        `The tag option to pass to npm publish. By default NPM will publish using the 'latest' tag, even if ` +
        `the package is older than the current latest, so in publishing workflows for older releases, providing ` +
        `a tag is important. When hotfix changes are made, this parameter defaults to 'hotfix'.`
    });
    this._npmAccessLevel = this.defineChoiceParameter({
      alternatives: ['public', 'restricted'],
      parameterLongName: '--set-access-level',
      parameterShortName: undefined,
      description:
        `By default, when Rush invokes "npm publish" it will publish scoped packages with an access level ` +
        `of "restricted". Scoped packages can be published with an access level of "public" by specifying ` +
        `that value for this flag with the initial publication. NPM always publishes unscoped packages with ` +
        `an access level of "public". For more information, see the NPM documentation for the "--access" ` +
        `option of "npm publish".`
    });

    // NPM pack tarball related parameters
    this._pack = this.defineFlagParameter({
      parameterLongName: '--pack',
      description:
        `Packs projects into tarballs instead of publishing to npm repository. It can only be used when ` +
        `--include-all is specified. If this flag is specified, NPM registry related parameters will be ignored.`
    });
    this._releaseFolder = this.defineStringParameter({
      parameterLongName: '--release-folder',
      argumentName: 'FOLDER',
      description:
        `This parameter is used with --pack parameter to provide customized location for the tarballs instead of ` +
        `the default value. `
    });
    // End of NPM pack tarball related parameters

    this._includeAll = this.defineFlagParameter({
      parameterLongName: '--include-all',
      parameterShortName: undefined,
      description:
        `If this flag is specified, all packages with shouldPublish=true in ${RushConstants.rushJsonFilename} ` +
        'or with a specified version policy ' +
        'will be published if their version is newer than published version.'
    });
    this._versionPolicy = this.defineStringParameter({
      parameterLongName: '--version-policy',
      argumentName: 'POLICY',
      description:
        'Version policy name. Only projects with this version policy will be published if used ' +
        'with --include-all.'
    });
    this._prereleaseName = this.defineStringParameter({
      parameterLongName: '--prerelease-name',
      argumentName: 'NAME',
      description:
        'Bump up to a prerelease version with the provided prerelease name. Cannot be used with --suffix'
    });
    this._partialPrerelease = this.defineFlagParameter({
      parameterLongName: '--partial-prerelease',
      parameterShortName: undefined,
      description:
        'Used with --prerelease-name. Only bump packages to a prerelease version if they have changes.'
    });
    this._suffix = this.defineStringParameter({
      parameterLongName: '--suffix',
      argumentName: 'SUFFIX',
      description: 'Append a suffix to all changed versions. Cannot be used with --prerelease-name.'
    });
    this._force = this.defineFlagParameter({
      parameterLongName: '--force',
      parameterShortName: undefined,
      description: 'If this flag is specified with --publish, packages will be published with --force on npm'
    });
    this._applyGitTagsOnPack = this.defineFlagParameter({
      parameterLongName: '--apply-git-tags-on-pack',
      description:
        `If specified with --publish and --pack, git tags will be applied for packages` +
        ` as if a publish was being run without --pack.`
    });
    this._commitId = this.defineStringParameter({
      parameterLongName: '--commit',
      parameterShortName: '-c',
      argumentName: 'COMMIT_ID',
      description:
        `Used in conjunction with git tagging -- apply git tags at the commit hash` +
        ` specified. If not provided, the current HEAD will be tagged.`
    });
    this._ignoreGitHooksParameter = this.defineFlagParameter({
      parameterLongName: '--ignore-git-hooks',
      description: `Skips execution of all git hooks. Make sure you know what you are skipping.`
    });
  }

  /**
   * Executes the publish action, which will read change request files, apply changes to package.jsons,
   */
  protected async runAsync(): Promise<void> {
    const currentlyInstalledVariant: string | undefined =
      await this.rushConfiguration.getCurrentlyInstalledVariantAsync();
    await PolicyValidator.validatePolicyAsync(
      this.rushConfiguration,
      this.rushConfiguration.defaultSubspace,
      currentlyInstalledVariant,
      { bypassPolicy: false }
    );

    // Example: "common\temp\publish-home"
    this._targetNpmrcPublishFolder = path.join(this.rushConfiguration.commonTempFolder, 'publish-home');

    const allPackages: ReadonlyMap<string, RushConfigurationProject> = this.rushConfiguration.projectsByName;

    if (this._regenerateChangelogs.value) {
      // eslint-disable-next-line no-console
      console.log('Regenerating changelogs');
      ChangelogGenerator.regenerateChangelogs(allPackages, this.rushConfiguration);
      return;
    }

    this._validate();

    this._addNpmPublishHome(this.rushConfiguration.isPnpm);

    const git: Git = new Git(this.rushConfiguration);
    const publishGit: PublishGit = new PublishGit(git, this._targetBranch.value);
    if (this._includeAll.value) {
      await this._publishAllAsync(publishGit, allPackages);
    } else {
      this._prereleaseToken = new PrereleaseToken(
        this._prereleaseName.value,
        this._suffix.value,
        this._partialPrerelease.value
      );
      await this._publishChangesAsync(git, publishGit, allPackages);
    }

    // eslint-disable-next-line no-console
    console.log('\n' + Colorize.green('Rush publish finished successfully.'));
  }

  /**
   * Validate some input parameters
   */
  private _validate(): void {
    if (this._pack.value && !this._includeAll.value) {
      throw new Error('--pack can only be used with --include-all');
    }
    if (this._releaseFolder.value && !this._pack.value) {
      throw new Error(`--release-folder can only be used with --pack`);
    }
    if (this._applyGitTagsOnPack.value && !this._pack.value) {
      throw new Error(`${this._applyGitTagsOnPack.longName} must be used with ${this._pack.longName}`);
    }
  }

  private async _publishChangesAsync(
    git: Git,
    publishGit: PublishGit,
    allPackages: ReadonlyMap<string, RushConfigurationProject>
  ): Promise<void> {
    const changeManager: ChangeManager = new ChangeManager(this.rushConfiguration);
    await changeManager.loadAsync(
      this.rushConfiguration.changesFolder,
      this._prereleaseToken,
      this._addCommitDetails.value
    );

    if (changeManager.hasChanges()) {
      const orderedChanges: IChangeInfo[] = changeManager.packageChanges;
      const tempBranchName: string = `publish-${Date.now()}`;

      // Make changes in temp branch.
      await publishGit.checkoutAsync(tempBranchName, true);

      this._setDependenciesBeforePublish();

      // Make changes to package.json and change logs.
      changeManager.apply(this._apply.value);
      await changeManager.updateChangelogAsync(this._apply.value);

      this._setDependenciesBeforeCommit();

      if (await git.hasUncommittedChangesAsync()) {
        // Stage, commit, and push the changes to remote temp branch.
        await publishGit.addChangesAsync(':/*');
        await publishGit.commitAsync(
          this.rushConfiguration.gitVersionBumpCommitMessage || DEFAULT_PACKAGE_UPDATE_MESSAGE,
          !this._ignoreGitHooksParameter.value
        );
        await publishGit.pushAsync(tempBranchName, !this._ignoreGitHooksParameter.value);

        this._setDependenciesBeforePublish();

        // Override tag parameter if there is a hotfix change.
        for (const change of orderedChanges) {
          if (change.changeType === ChangeType.hotfix) {
            this._hotfixTagOverride = 'hotfix';
            break;
          }
        }

        // Publish projects via their registered publish providers.
        for (const change of orderedChanges) {
          if (change.changeType && change.changeType > ChangeType.dependency) {
            const project: RushConfigurationProject | undefined = allPackages.get(change.packageName);
            if (project) {
              await this._publishProjectViaProvidersAsync(project);
            } else {
              // eslint-disable-next-line no-console
              console.log(`Skip ${change.packageName}. Failed to find its project.`);
            }
          }
        }

        this._setDependenciesBeforeCommit();

        // Create and push appropriate Git tags.
        await this._gitAddTagsAsync(publishGit, orderedChanges);
        await publishGit.pushAsync(tempBranchName, !this._ignoreGitHooksParameter.value);

        // Now merge to target branch.
        await publishGit.checkoutAsync(this._targetBranch.value!);
        await publishGit.pullAsync(!this._ignoreGitHooksParameter.value);
        await publishGit.mergeAsync(tempBranchName, !this._ignoreGitHooksParameter.value);
        await publishGit.pushAsync(this._targetBranch.value!, !this._ignoreGitHooksParameter.value);
        await publishGit.deleteBranchAsync(tempBranchName, true, !this._ignoreGitHooksParameter.value);
      } else {
        await publishGit.checkoutAsync(this._targetBranch.value!);
        await publishGit.deleteBranchAsync(tempBranchName, false, !this._ignoreGitHooksParameter.value);
      }
    }
  }

  private async _publishAllAsync(
    git: PublishGit,
    allPackages: ReadonlyMap<string, RushConfigurationProject>
  ): Promise<void> {
    // eslint-disable-next-line no-console
    console.log(`Rush publish starts with includeAll and version policy ${this._versionPolicy.value}`);

    let updated: boolean = false;

    for (const [packageName, packageConfig] of allPackages) {
      if (
        packageConfig.shouldPublish &&
        (!this._versionPolicy.value || this._versionPolicy.value === packageConfig.versionPolicyName)
      ) {
        const applyTagAsync: (apply: boolean) => Promise<void> = async (apply: boolean): Promise<void> => {
          if (!apply) {
            return;
          }

          const packageVersion: string = packageConfig.packageJson.version;

          // Do not create a new tag if one already exists, this will result in a fatal error
          if (await git.hasTagAsync(packageConfig)) {
            // eslint-disable-next-line no-console
            console.log(
              `Not tagging ${packageName}@${packageVersion}. A tag already exists for this version.`
            );
            return;
          }

          await git.addTagAsync(
            !!this._publish.value,
            packageName,
            packageVersion,
            this._commitId.value,
            this._prereleaseName.value
          );
          updated = true;
        };

        if (this._pack.value) {
          // packs to tarball instead of publishing to NPM repository
          await this._npmPackAsync(packageName, packageConfig);
          await applyTagAsync(this._applyGitTagsOnPack.value);
        } else {
          const published: boolean = await this._publishProjectViaProvidersAsync(packageConfig);
          if (published) {
            await applyTagAsync(true);
          } else {
            // eslint-disable-next-line no-console
            console.log(`Skip ${packageName}. Not updated.`);
          }
        }
      }
    }

    if (updated) {
      await git.pushAsync(this._targetBranch.value!, !this._ignoreGitHooksParameter.value);
    }
  }

  private async _gitAddTagsAsync(git: PublishGit, orderedChanges: IChangeInfo[]): Promise<void> {
    for (const change of orderedChanges) {
      if (
        change.changeType &&
        change.changeType > ChangeType.dependency &&
        this.rushConfiguration.projectsByName.get(change.packageName)!.shouldPublish
      ) {
        await git.addTagAsync(
          !!this._publish.value && !this._registryUrl.value,
          change.packageName,
          change.newVersion!,
          this._commitId.value,
          this._prereleaseName.value
        );
      }
    }
  }

  /**
   * Publish a project to all of its registered publish targets.
   * Returns true if at least one target was published.
   */
  private async _publishProjectViaProvidersAsync(project: RushConfigurationProject): Promise<boolean> {
    let published: boolean = false;
    const version: string = project.packageJsonEditor.version;
    const tag: string | undefined = this._npmTag.value || this._hotfixTagOverride || undefined;
    const dryRun: boolean = !this._publish.value;
    const logger: Logger = new Logger({
      loggerName: 'publish',
      terminalProvider: new ConsoleTerminalProvider({ verboseEnabled: false }),
      getShouldPrintStacks: () => false
    });

    for (const target of project.publishTargets) {
      if (target === 'none') {
        continue;
      }

      const provider: IPublishProvider = await this._getProviderAsync(target, project.packageName);
      const providerConfig: Record<string, unknown> | undefined = await this._getProviderConfigAsync(
        project,
        target
      );

      // Check if the version already exists at this target
      if (!this._force.value && (await provider.checkExistsAsync({ project, version, providerConfig }))) {
        // eslint-disable-next-line no-console
        console.log(`Skip ${project.packageName}@${version} for target "${target}". Already exists.`);
        continue;
      }

      await provider.publishAsync({
        projects: [
          {
            project,
            newVersion: version,
            previousVersion: version,
            changeType: ChangeType.none,
            providerConfig
          }
        ],
        tag,
        dryRun,
        logger
      });
      published = true;
    }

    return published;
  }

  private async _npmPackAsync(packageName: string, project: RushConfigurationProject): Promise<void> {
    const args: string[] = ['pack'];
    const env: { [key: string]: string | undefined } = PublishUtilities.getEnvArgs();

    await PublishUtilities.execCommandAsync({
      shouldExecute: this._publish.value,
      command: this.rushConfiguration.packageManagerToolFilename,
      args,
      workingDirectory: project.publishFolder,
      environment: env
    });

    if (this._publish.value) {
      // Copy the tarball the release folder
      const tarballName: string = this._calculateTarballName(project);
      const tarballPath: string = path.join(project.publishFolder, tarballName);
      const destFolder: string = this._releaseFolder.value
        ? this._releaseFolder.value
        : path.join(this.rushConfiguration.commonTempFolder, 'artifacts', 'packages');

      FileSystem.move({
        sourcePath: tarballPath,
        destinationPath: path.join(destFolder, tarballName),
        overwrite: true
      });
    }
  }

  private _calculateTarballName(project: RushConfigurationProject): string {
    // Same logic as how npm forms the tarball name
    const packageName: string = project.packageName;
    const name: string = packageName[0] === '@' ? packageName.substr(1).replace(/\//g, '-') : packageName;

    if (this.rushConfiguration.packageManager === 'yarn') {
      // yarn tarballs have a "v" before the version number
      return `${name}-v${project.packageJson.version}.tgz`;
    } else {
      return `${name}-${project.packageJson.version}.tgz`;
    }
  }

  private _setDependenciesBeforePublish(): void {
    for (const project of this.rushConfiguration.projects) {
      if (!this._versionPolicy.value || this._versionPolicy.value === project.versionPolicyName) {
        const versionPolicy: VersionPolicy | undefined = project.versionPolicy;

        if (versionPolicy) {
          versionPolicy.setDependenciesBeforePublish(project.packageName, this.rushConfiguration);
        }
      }
    }
  }

  private _setDependenciesBeforeCommit(): void {
    for (const project of this.rushConfiguration.projects) {
      if (!this._versionPolicy.value || this._versionPolicy.value === project.versionPolicyName) {
        const versionPolicy: VersionPolicy | undefined = project.versionPolicy;

        if (versionPolicy) {
          versionPolicy.setDependenciesBeforePublish(project.packageName, this.rushConfiguration);
        }
      }
    }
  }

  /**
   * Load and cache the riggable config/publish.json for a given project.
   */
  private async _loadPublishConfigAsync(
    project: RushConfigurationProject
  ): Promise<IPublishJson | undefined> {
    const cached: IPublishJson | undefined | null = this._publishConfigCache.get(project.packageName);
    if (cached !== undefined) {
      // Cached result: null means we tried loading but the file doesn't exist
      return cached ?? undefined;
    }

    const terminal: Terminal = new Terminal(new ConsoleTerminalProvider({ verboseEnabled: false }));
    const rigConfig: RigConfig = await RigConfig.loadForProjectFolderAsync({
      projectFolderPath: project.projectFolder
    });

    const publishJson: IPublishJson | undefined =
      await PUBLISH_CONFIGURATION_FILE.tryLoadConfigurationFileForProjectAsync(
        terminal,
        project.projectFolder,
        rigConfig
      );

    // Store null for "not found" to distinguish from "not yet loaded"
    this._publishConfigCache.set(project.packageName, publishJson ?? undefined);
    return publishJson;
  }

  /**
   * Get or create a publish provider for the given target name.
   */
  private async _getProviderAsync(targetName: string, packageName: string): Promise<IPublishProvider> {
    let provider: IPublishProvider | undefined = this._providerCache.get(targetName);
    if (!provider) {
      const factory: (() => Promise<IPublishProvider>) | undefined =
        this.rushSession.getPublishProviderFactory(targetName);
      if (!factory) {
        throw new Error(
          `No publish provider registered for target "${targetName}". ` +
            `Project "${packageName}" has publishTarget including "${targetName}" ` +
            `but no plugin has registered a provider for it.`
        );
      }
      provider = await factory();
      this._providerCache.set(targetName, provider);
    }
    return provider;
  }

  /**
   * Get the provider config for a project+target, merging CLI flag overrides for npm.
   */
  private async _getProviderConfigAsync(
    project: RushConfigurationProject,
    targetName: string
  ): Promise<Record<string, unknown> | undefined> {
    const publishJson: IPublishJson | undefined = await this._loadPublishConfigAsync(project);
    const baseConfig: Record<string, unknown> | undefined = publishJson?.providers?.[targetName];

    // For npm target, merge CLI flag overrides on top of config/publish.json values
    if (targetName === 'npm') {
      const cliOverrides: Record<string, unknown> = {};
      if (this._registryUrl.value) {
        cliOverrides.registryUrl = this._registryUrl.value;
      }
      if (this._npmAuthToken.value) {
        cliOverrides.npmAuthToken = this._npmAuthToken.value;
      }
      if (this._npmAccessLevel.value) {
        cliOverrides.access = this._npmAccessLevel.value;
      }
      if (Object.keys(cliOverrides).length > 0) {
        return { ...baseConfig, ...cliOverrides };
      }
    }

    return baseConfig;
  }

  private _addNpmPublishHome(supportEnvVarFallbackSyntax: boolean): void {
    // Create "common\temp\publish-home" folder, if it doesn't exist
    Utilities.createFolderWithRetry(this._targetNpmrcPublishFolder);

    // Copy down the committed "common\config\rush\.npmrc-publish" file, if there is one
    Utilities.syncNpmrc({
      sourceNpmrcFolder: this.rushConfiguration.commonRushConfigFolder,
      targetNpmrcFolder: this._targetNpmrcPublishFolder,
      useNpmrcPublish: true,
      supportEnvVarFallbackSyntax
    });
  }
}
