version: '3.7'

services:
  minio:
    image: quay.io/minio/minio:RELEASE.2022-01-28T02-28-16Z
    command: server --console-address ":9001" /data
    ports:
      - '9000:9000'
      - '9001:9001'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 20s
      retries: 3
    volumes:
      - ./s3data:/data
