// Copyright (c) Microsoft Corporation. All rights reserved. Licensed under the MIT license.
// See LICENSE in the project root for license information.

import type { RushConfigurationProject } from '../../api/RushConfigurationProject';
import type { IPhase } from '../../api/CommandLineConfiguration';
import type { IOperationRunner } from './IOperationRunner';
import type { IOperationSettings } from '../../api/RushProjectConfiguration';
import { type Parallelism, parseParallelismPercent } from './ParseParallelism';

/**
 * State for the `enabled` property of an `Operation`.
 *
 * - `true`: The operation should be executed if it or any dependencies changed.
 * - `false`: The operation should be skipped.
 * - `"ignore-dependency-changes"`: The operation should be executed if there are local changes in the project,
 *   otherwise it should be skipped. This is useful for operations like "test" where you may want to skip
 *   testing projects that haven't changed.
 * @alpha
 */
export type OperationEnabledState = boolean | 'ignore-dependency-changes';

/**
 * Options for constructing a new Operation.
 * @alpha
 */
export interface IOperationOptions {
  /**
   * The Rush phase associated with this Operation
   */
  phase: IPhase;

  /**
   * The Rush project associated with this Operation
   */
  project: RushConfigurationProject;

  /**
   * If set to false, this operation will be skipped during evaluation (return OperationStatus.Skipped).
   * This is useful for plugins to alter the scope of the operation graph across executions,
   * e.g. to enable or disable unit test execution, or to include or exclude dependencies.
   *
   * The special value "ignore-dependency-changes" can be used to indicate that this operation should only
   * be executed if there are local changes in the project. This is useful for operations like
   * "test" where you may want to skip testing projects that haven't changed.
   *
   * The default value is `true`, meaning the operation will be executed if it or any dependencies change.
   */
  enabled?: OperationEnabledState;

  /**
   * When the scheduler is ready to process this `Operation`, the `runner` implements the actual work of
   * running the operation.
   */
  runner?: IOperationRunner | undefined;

  /**
   * Settings defined in the project configuration for this operation, can be overridden.
   */
  settings?: IOperationSettings | undefined;

  /**
   * {@inheritDoc Operation.logFilenameIdentifier}
   */
  logFilenameIdentifier: string;
}

/**
 * The `Operation` class is a node in the dependency graph of work that needs to be scheduled by the
 * `OperationGraph`. Each `Operation` has a `runner` member of type `IOperationRunner`, whose
 * implementation manages the actual process of running a single operation.
 *
 * The graph of `Operation` instances will be cloned into a separate execution graph after processing.
 *
 * @alpha
 */
export class Operation {
  /**
   * The Rush phase associated with this Operation
   */
  public readonly associatedPhase: IPhase;

  /**
   * The Rush project associated with this Operation
   */
  public readonly associatedProject: RushConfigurationProject;

  /**
   * A set of all operations which depend on this operation.
   */
  public readonly consumers: ReadonlySet<Operation> = new Set<Operation>();

  /**
   * A set of all dependencies which must be executed before this operation is complete.
   */
  public readonly dependencies: ReadonlySet<Operation> = new Set<Operation>();

  /**
   * This property is used in the name of the filename for the logs generated by this
   * operation. This is a filesystem-safe version of the phase name. For example,
   * an operation for a phase with name `_phase:compile` has a `logFilenameIdentifier` of `_phase_compile`.
   */
  public logFilenameIdentifier: string;

  /**
   * When the scheduler is ready to process this `Operation`, the `runner` implements the actual work of
   * running the operation.
   */
  public runner: IOperationRunner | undefined = undefined;

  /**
   * The concurrency weight for this operation. When coerced to an integer via `coerceParallelism`,
   * this value represents how many concurrency slots the operation consumes while running.
   *
   * May be specified as:
   * - A raw `number`: used directly as the slot count (e.g. `2` consumes two slots).
   * - An `IParallelismScalar` (e.g. `{ scalar: 0.5 }`): coerced relative to the graph's
   *   configured `maxParallelism` at execution time, so the weight scales with the available
   *   concurrency rather than being fixed at parse time.
   *
   * Coerced values guide scheduling as follows:
   * - `1` slot: typical operation consuming one logical thread.
   * - `> 1` slots: operation that spawns multiple threads or requires significant RAM; reserving
   *   extra slots prevents overloading the machine (e.g. a whole-program bundler or a test suite
   *   that runs its own internal parallelism).
   * - `0` slots: effectively free (e.g. a no-op or cache-restore step).
   */
  public weight: Parallelism;

  /**
   * Get the operation settings for this operation, defaults to the values defined in
   *  the project configuration.
   */
  public settings: IOperationSettings | undefined = undefined;

  /**
   * If set to false, this operation will be skipped during evaluation (return OperationStatus.Skipped).
   * This is useful for plugins to alter the scope of the operation graph across executions,
   * e.g. to enable or disable unit test execution, or to include or exclude dependencies.
   *
   * The special value "ignore-dependency-changes" can be used to indicate that this operation should only
   * be executed if there are local changes in the project. This is useful for operations like
   * "test" where you may want to skip testing projects that haven't changed.
   *
   * The default value is `true`, meaning the operation will be executed if it or any dependencies change.
   */
  public enabled: OperationEnabledState;

  public constructor(options: IOperationOptions) {
    const { phase, project, runner, settings, logFilenameIdentifier } = options;
    this.associatedPhase = phase;
    this.associatedProject = project;
    this.runner = runner;
    this.settings = settings;
    this.logFilenameIdentifier = logFilenameIdentifier;
    this.enabled = options.enabled ?? true;
    this.weight = _getFinalWeight(
      settings?.weight ?? 1,
      runner?.name ?? `${project.packageName} (${phase.name}`
    );
  }

  /**
   * The name of this operation, for logging.
   */
  public get name(): string {
    const { runner } = this;
    if (!runner) {
      throw new Error(`Cannot get name of an Operation that does not yet have a runner.`);
    }
    return runner.name;
  }

  /**
   * If set to true, this operation is considered a no-op and can be considered always skipped for analysis purposes.
   */
  public get isNoOp(): boolean {
    const { runner } = this;
    if (!runner) {
      throw new Error(`Cannot get isNoOp of an Operation that does not yet have a runner.`);
    }
    return !!runner.isNoOp;
  }

  /**
   * Adds the specified operation as a dependency and updates the consumer list.
   */
  public addDependency(dependency: Operation): void {
    // Cast internally to avoid adding the overhead of getters
    (this.dependencies as Set<Operation>).add(dependency);
    (dependency.consumers as Set<Operation>).add(this);
  }

  /**
   * Deletes the specified operation as a dependency and updates the consumer list.
   */
  public deleteDependency(dependency: Operation): void {
    // Cast internally to avoid adding the overhead of getters
    (this.dependencies as Set<Operation>).delete(dependency);
    (dependency.consumers as Set<Operation>).delete(this);
  }
}

function _getFinalWeight(rawWeight: string | number, context: string): Parallelism {
  if (typeof rawWeight === 'number') {
    // Explicit numeric weight allows any value.
    return rawWeight;
  } else {
    try {
      return { scalar: parseParallelismPercent(rawWeight) };
    } catch (err) {
      throw new Error(`Invalid weight for operation "${context}": ${err.message}`);
    }
  }
}
