parameters:
  - name: BuildParameters
    type: string
    default: ''

steps:
  - script: 'git config --local user.email rushbot@users.noreply.github.com'
    displayName: 'git config email'

  - script: 'git config --local user.name Rushbot'
    displayName: 'git config name'

  - template: /common/config/azure-pipelines/templates/install-run-rush.yaml@self
    parameters:
      Arguments: 'change --verify'
      DisplayName: 'Verify Change Logs'

  - template: /common/config/azure-pipelines/templates/install-run-rush.yaml@self
    parameters:
      Arguments: 'install'
      DisplayName: 'Rush Install'

  # - bash: |
  #     /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  #     echo ">>> Started xvfb"
  #   displayName: Start xvfb
  #   condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))

  - template: /common/config/azure-pipelines/templates/install-run-rush.yaml@self
    parameters:
      Arguments: 'retest --verbose --production ${{ parameters.BuildParameters }}'
      DisplayName: 'Rush retest (install-run-rush)'

  - script: 'npm run test'
    workingDirectory: 'build-tests/rush-package-manager-integration-test'
    displayName: 'Run package manager integration tests'
