parameters:
  - name: VersionPolicyName
    type: string
  - name: BranchName
    type: string
    default: $(Build.SourceBranchName)

steps:
  - template: /common/config/azure-pipelines/templates/install-run-rush.yaml@self
    parameters:
      Arguments: >
        version
        --bump
        --version-policy ${{ parameters.VersionPolicyName }}
        --target-branch ${{ parameters.BranchName }}
      DisplayName: 'Rush Version (Policy: ${{ parameters.VersionPolicyName }})'
