parameters:
  - name: VersionPolicyName
    type: string

steps:
  - template: /common/config/azure-pipelines/templates/install-run-rush.yaml@self
    parameters:
      Arguments: >
        version
        --bump
        --version-policy ${{ parameters.VersionPolicyName }}
      DisplayName: 'Rush Version (Policy: ${{ parameters.VersionPolicyName }})'
