# Runs install-run-rush.js with the specified CLI arguments and sets the
# INSTALL_RUN_RUSH_LOCKFILE_PATH environment variable.
parameters:
  - name: Arguments
    type: string
  - name: DisplayName
    type: string
  - name: Condition
    type: string
    default: ''
  - name: NpmAuthToken
    type: string
    default: ''
  - name: RepoPath
    type: string
    default: '$(Build.SourcesDirectory)'
  - name: DisableInstallRunRushLockfile
    type: boolean
    default: false

steps:
  - script: 'node common/scripts/install-run-rush.js ${{ parameters.Arguments }}'
    displayName: '${{ parameters.DisplayName }}'
    workingDirectory: ${{ parameters.RepoPath }}
    ${{ if ne(parameters.Condition, '') }}:
      condition: ${{ parameters.Condition }}
    env:
      ${{ if not(parameters.DisableInstallRunRushLockfile) }}:
        INSTALL_RUN_RUSH_LOCKFILE_PATH: ${{ parameters.RepoPath }}/common/config/validation/rush-package-lock.json
      ${{ if ne(parameters.NpmAuthToken, '') }}:
        NPM_AUTH_TOKEN: ${{ parameters.NpmAuthToken }}
