parameters:
  - name: NodeMajorVersion
    type: number
    default: 20

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '${{ parameters.NodeMajorVersion }}.x'
    displayName: 'Install Node.js ${{ parameters.NodeMajorVersion }}'
