parameters:
  - name: VersionPolicyName
    type: string
  - name: PackageCohort
    type: string

steps:
  - template: /common/config/azure-pipelines/templates/install-run-rush.yaml@self
    parameters:
      Arguments: '--help'
      DisplayName: 'Install Rush'

  - template: /common/config/azure-pipelines/templates/install-run-rush.yaml@self
    parameters:
      Arguments: >
        pack
        --pack-destination $(Build.ArtifactStagingDirectory)/packages
      DisplayName: 'Rush Pack (Policy: ${{ parameters.VersionPolicyName }})'

  - script: >
      node common/scripts/publish-cohort.js filter-packages
      --cohort ${{ parameters.PackageCohort }}
      --packages-path $(Build.ArtifactStagingDirectory)/packages
    displayName: 'Filter unpublished ${{ parameters.PackageCohort }} packages'
