parameters:
  # Only the packages belonging to this version policy are packed.
  - name: VersionPolicyName
    type: string

steps:
  - template: /common/config/azure-pipelines/templates/install-run-rush.yaml@self
    parameters:
      Arguments: '--help'
      DisplayName: 'Install Rush'

  - bash: 'rm -f "$HOME/.npmrc"'
    displayName: 'Clear user npmrc for publish'

  - template: /common/config/azure-pipelines/templates/install-run-rush.yaml@self
    parameters:
      Arguments: >
        publish
        --publish
        --pack
        --include-all
        --version-policy ${{ parameters.VersionPolicyName }}
        --release-folder $(Build.ArtifactStagingDirectory)/packages
      DisplayName: 'Rush Pack (Policy: ${{ parameters.VersionPolicyName }})'
