steps:
  - template: /common/config/azure-pipelines/templates/install-run-rush.yaml@self
    parameters:
      Arguments: >
        record-published-versions
        --output-path $(Build.ArtifactStagingDirectory)/published-versions/published-versions.json
      DisplayName: 'Record Published Versions'

  - template: /common/config/azure-pipelines/templates/run-repo-toolbox.yaml@self
    parameters:
      Arguments: >
        collect-project-files
        --subfolder temp/json-schemas
        --output-path $(Build.ArtifactStagingDirectory)/json-schemas
      DisplayName: 'Collect JSON Schemas'

  - template: /common/config/azure-pipelines/templates/run-repo-toolbox.yaml@self
    parameters:
      Arguments: >
        collect-project-files
        --subfolder temp/api
        --output-path $(Build.ArtifactStagingDirectory)/api
      DisplayName: 'Collect API review files'
