parameters:
  - name: VersionPolicyName
    type: string
  - name: BranchName
    type: string
    default: $(Build.SourceBranchName)

steps:
  - template: /common/config/azure-pipelines/templates/install-run-rush.yaml@self
    parameters:
      Arguments: >
        publish
        --apply
        --publish
        --include-all
        --target-branch ${{ parameters.BranchName }}
        --add-commit-details --set-access-level public
      DisplayName: 'Rush Publish (Policy: ${{ parameters.VersionPolicyName }})'
      NpmAuthToken: $(npmToken)
